src/components/Content/Reference/ReferencePanel.js, src/components/Content/Reference/ReferenceSelector.js, src/components/Content/Reference/core/setup.js, src/components/Content/Reference/useStyles.js
Added the basic ReferecePanel, ReferenceSelector and the useStyle(css) components.
=> Basic setup of Reference Panel

src/components/Content/Reference/ReferenceSelector.js, src/components/Content/Reference/core/setup.js
added mobx to identify the change of the bible in Reference panel and render it. #15
=> Added mobx to render the component

src/components/Content/Reference/ReferencePanel.js, src/components/Content/Reference/core/setup.js, src/components/Content/Reference/useStyles.js, src/components/Content/Translation/TranslationPanel.js, src/components/Content/Translation/TranslationSettings.js, src/components/NavBar/AppBar.js
- Reference panel tweaks to accommodate translation panel
=> Added import translationsettings path fix and reference panel tweaks

src/components/Content/Reference/ReferenceSettings.js, src/components/NavBar/AppBar.js, src/core/usfm_import.js, src/core/usfm_to_json.js
Made a reference_settings component with import functionality and settings.
=> Added reference settings component

src/components/AutographaStore.js, src/components/Content/Reference/ReferenceSettings.js, src/components/NavBar/AppBar.js, src/components/Reports/ImportReport.js, src/core/usfm_import.js, src/core/usfm_to_json.js
Removed the ImportReport component call from the AppBar and connected the Report with reference import. AutographaStore is been used for storing the report values and displaying the values through the ImportReport component. #4
=> Reference report

src/components/Content/Translation/TranslationImport.js, src/core/usfm_import.js
Connected translation import with the ImportReport component, using props and AutographaStore the values is been passed. #4
=> Connected Import Report with Translation Import

src/components/Search.js
The search component is been added with the find and replace functionality. The functionality is working and tested. #22
=> Find and replace functionality is been added

src/components/Loader/Loader.js, src/components/Loader/loader.css
Added loader component with css. #4
=> Adding loader component

src/components/AutographaStore.js, src/components/Content/Reference/ReferencePanel.js, src/components/Content/Reference/core/setup.js, src/components/Content/Reference/useStyles.js, src/components/Content/Translation/TranslationPanel.js, src/components/Content/Translation/core/TranslationSetUp.js, src/components/Footer/FontSlider.js, src/components/Footer/Footer.js, src/components/NavBar/AppBar.js, src/components/NavBar/BookChapterNavigation.js, src/components/NavBar/BookNameEditor.js
=> Footer with funtional 3 layouts and basic styles, font slider

src/assets/icons/backup_white.svg, src/components/Download/Download.js, src/components/Download/HtmlExport.js, src/components/Download/UsfmExport.js, src/components/NavBar/AppBar.js, src/core/convert/export_css.js, src/core/convert/export_html.js
Created a Download component with other child components, USFM export and HTML (1&2 column) export functionalities. #6
=> created a download component

package.json
Lint script to show error and warning report and fix for the same error
`npm run lint`
`npm run lint:fix`
=> lint report and fix

package-lock.json, src/components/Content/Reference/ReferencePanel.js, src/components/Content/Translation/TranslationPanel.js, src/components/Footer/FontSlider.js
Changed font slider functionality that touches DOM and added simple functions
=> refactored and removed all fontchange dom properties

src/components/Sync/GetProjects.js, src/components/Sync/Paratext/Import.js, src/components/Sync/Paratext/ProjectListRow.js, src/components/Sync/Paratext/Upload.js, src/components/Sync/SignIn.js, src/components/Sync/Sync.js
Fixed upload issue and made few UI changes.
Cleaned the code and pushed it. #50
=> Paratext sync

__mocks__/electron.js, package-lock.json, package.json, src/App.test.js, src/components/Content/Reference/ReferencePanel.js, src/components/Content/Reference/ReferencePanel.test.js, src/components/Content/Translation/TranslationSettings.js, src/components/Content/Translation/TranslationSettings.test.js, src/components/Footer/FontSlider.js, src/components/Footer/footerslider.test.js, src/components/NavBar/DiffChecker.js, src/core/data-provider.js, src/core/usfm_to_json.js, src/setupTests.js, test/testUtils.js
jest setup with mock and test for refpanel and fontslider
=> Jest integration1

src/components/Content/Reference/ReferencePanel.js, src/components/Content/Reference/ReferenceSettings.js, src/components/Content/Translation/TranslationImport.js, src/components/Content/Translation/TranslationSettings.js, src/components/NavBar/AppBar.js, src/components/Settings.js
A code change to make translation settings independent
=> added common settings file to accomodate all the settings addons

package-lock.json, package.json, src/components/Content/Reference/ReferenceManage.js, src/components/Content/Reference/ReferenceSettings.js, src/components/Settings.js, src/contexts/SetupContext.js
Added Reference management tabs with all the corresponding functionality (Rename, cancel, delete references)
=> Reference manage

src/components/Content/Translation/TranslationSettings.js, src/contexts/SettingContext.js, src/core/AutoBackup.js
Added auto-backup feature to store data locally, tested it. #41
This feature allows the user to store the data automatically daily/weekly.
=> Added auto-backup feature

src/components/Content/Reference/ReferencePanel.js, src/components/Content/Reference/core/setup.js, src/components/Content/Translation/TranslationPanel.js
Added UI for displaying diff-count, the difference is been shown for all layouts.
=> Displaying difference count

src/components/Content/Reference/ReferenceManage.js, src/components/Footer/Footer.js
This is persisted from old code. The language code gets disappeared once we update the reference list.
=> Referencemange language code fix 

src/components/Content/Reference/ReferenceSettings.js
Stored reference version in DB for displaying the values correctly in Reference Management. #65
=> Stored reference version in db

src/components/About.js
Updated About.js UI from modal to Dialog and updated the App version value from static to dynamic (fetch from package.json).
=> Updated about component with Dialog UI and Dynamic values

package.json, src/components/AutographaStore.js, src/components/Content/Translation/FontChange.js, src/components/Content/Translation/TranslationPanel.js, src/translations/ar.js, src/translations/en.js, src/translations/es.js, src/translations/hi.js, src/translations/pt.js
Added font change feature for translation panel along with required translations.
=> Added font change feature for translation panel

package.json, public/electron.js, public/index.html, src/components/TranslationHelp/TranslationHelp.js
=> Added auto update feature tested with private repo updates as expected

src/Audio/components/BottomBar/BottomBar.js, src/Audio/context/StoreContext.js, src/Audio/core/ConcatAudio.js, src/components/Content/Translation/TranslationPanel.js, src/components/Content/Translation/helpers.js, src/components/Reports/ImportReport.js, src/components/Sync/Paratext/ProjectListRow.js, src/core/FormatNumber.js, src/core/convert/export_html.js
Removed warnings `Expected to return a value in arrow function` by replacing the map loops with forEach.
=> Replaced all map loops with forEach

src/components/Content/Translation/FontChange.js
Multiple rendering was slowing down the app, solved the issue by rendering the font change component only once when the app gets loaded. #72
=> Solved- App gets slowdown with font function

package-lock.json, package.json, src/components/AutographaStore.js, src/components/ProjectsPane/Profile.js, src/components/ProjectsPane/Projects.js, src/components/ProjectsPane/ProjectsDrawer.js, src/components/main.js, test/testUtils.js
Projects List pane with some data persistence, avatar handling to the profile page
=> Projects list pane

src/components/Signup/Signup.js
Adding the signup UI and Validation.
=> Adding the signup UI

src/components/ProjectsPane/Projects.js
Sorting asc and desc for date and relative time fixed
=> Date and last view sort fix

src/components/ProjectsPane/Projects.js, src/components/ProjectsPane/ProjectsDrawer.js, src/components/ProjectsPane/TableData.js, src/components/tests/profile.test.js, src/components/tests/projects.test.js
Added test for each function with dom check using RTL
=> Test for all functionality in the project pane

src/components/Login/Login.js, src/components/Login/Login.test.js
Added test cases for the login UI.
=> Adding test in Login

src/components/Sync/Sync.js
Removed unwanted and consoles and imports.
=> Implementing material-UI updates

src/components/Signup/Signup.js, src/components/Signup/Signup.test.js
Added the test cases and log for Signup
=> Signup test and logs

src/components/Signup/Signup.js, src/components/Signup/Signup.test.js, src/core/handleJson.js, src/core/hashing..js
Updated Signup component
> Storing the user details on signup to local than to local forage.
> Before storing the data, the password is been hashed.
> Added few validations like user already exists or not.
=> Signup localforage

renderer/src/components/ApplicationBar/CustomDialog.js, renderer/src/components/ApplicationBar/tests/CustomDialog.test.js, renderer/src/components/ApplicationBar/useStyles.js
Added custom dialogs with a set of props to receive along with test cases and lint fix
=> Custom dialog

.env, package.json, pages/index.js, pages/login.js, pages/signup.js, renderer/src/logger.js
Added setting minor changes for electron next to work as a web application
=> Configured for web application

package-lock.json, package.json, renderer/pages/index.js, renderer/pages/login.js, renderer/src/components/Home.js, renderer/src/components/Login/AuthenticationContextProvider.js, renderer/src/components/Login/Login.js, renderer/src/components/Login/Login.test.js, renderer/src/components/Login/useAuthentication.js, renderer/src/components/Signup/Signup.js, renderer/src/core/handleJson.js, renderer/src/core/handleLogin.js, renderer/src/core/hashing.js, renderer/src/core/hashing.test.js
Offline Login/Signup flow with context and hooks, used JWT token for authentication purpose,
=> Offline flow with test and logs

package-lock.json, renderer/src/components/Login/Login.js, renderer/src/components/Login/Login.test.js, renderer/src/core/handleElectron.js
Differentiated the login flow in electron and browser by checking the app is currently working on electron or browser, with this condition login works without app break.
=> Finding out whether the app is running on electron or browser

package-lock.json, pages/index.js, renderer/src/components/Login/CustomLogin.js, renderer/src/components/Login/Login.js, renderer/src/components/Login/tests/CustomLogin.test.js, renderer/src/components/Login/tests/Login.test.js
Adding Custom Login UI and offline flow.
=> Custom login

.gitignore, renderer/src/components/ProjectsPage/CreateProject/NewProject.js, renderer/src/components/ProjectsPage/Projects/SearchData.js, renderer/src/components/ProjectsPage/Projects/StarredProjects.js, renderer/src/components/ProjectsPage/Projects/useProjectsSort.js, renderer/src/components/ProjectsPage/ProjectsContext/ProjectContext.js, renderer/src/components/ProjectsPage/ProjectsDrawer.js, renderer/src/components/Search/SearchForm.js, renderer/src/components/Search/SearchForm.test.js, renderer/src/core/projects/fetchProjectsMeta.js, renderer/src/core/projects/saveProjetcsMeta.js
> Code for project fetch offline
> handling fetch display and search
> creating duplicate search state, handling reloads with history
> Seamless flow from `new project` to `projectsTab`
=> Projectstab seamless offline flow 

main/preload.js, package-lock.json, pages/error.js, pages/index.js, renderer/src/components/Error/Error.js, renderer/src/components/Login/Login.js, renderer/src/components/Login/useAuthentication.js, renderer/src/components/ProjectsPage/Projects/useProjectsSort.js, renderer/src/components/Signup/Signup.js, renderer/src/components/Signup/useApi.js, renderer/src/config.json, renderer/src/core/handleLogin.js
Complete login and signup flow for offline and web online with Kratos. 
Added test and logs.
The login and signup are being Bypassed for UI development. #80 #81
=> login and signup using Kratos

package-lock.json, package.json, pages/home.js, renderer/environment.js, renderer/src/components/ApplicationBar/CustomDialog.js, renderer/src/components/EditorPage/Navigation/BibleNavigationInit.js, renderer/src/components/EditorPage/Navigation/BookNavigation.js, renderer/src/components/ProjectsPage/ProjectsDrawer.js, renderer/src/components/main.js
Code for bible navigation along with events handling and basic ag demo ui.
=> Biblenavigation

pages/home.js, renderer/pages/home.js, renderer/src/components/ApplicationBar/Avatar.js, renderer/src/components/ApplicationBar/CustomDialog.js, renderer/src/components/ApplicationBar/useStyles.js, renderer/src/components/EditorPage/Navigation/BookNavigation.js, renderer/src/components/EditorPage/Navigation/CustomBooksTab.js, renderer/src/components/ProjectsPage/Profile/Profile.js
* Avatar component with an offline, online badge, normal mode
* Custom Dialogs that can take subtitles and sub contents
* Navigation component sort capable based on state trigger
=> Custom Avatar component, Dialog and Navigation Book Sort

package-lock.json, package.json, postcss.config.js, tailwind.config.js
* Fix for config tailwind module purge
* Tailwind JIT plugin added inside post CSS for OnDemand CSS build and for better perform
=>  jit plugin  and build version css fix

.vscode/settings.json, package-lock.json, renderer/src/components/Login/Login.js, renderer/src/components/Signup/Signup.js, renderer/src/components/Signup/Signup.test.js, renderer/src/components/Sync/Dropzone/Dropzone.js, renderer/src/components/Sync/Gitea/FileList.js, renderer/src/components/Sync/Sync.js
Changed signup UI by accessing custom login UI. #81
=> Changed the signup UI

docs/AutographaTestDoc.md
=> Adding autographa Testing Document

package-lock.json, pages/_app.js, renderer/src/components/Sync/ProjectFileBrowser.js, renderer/src/components/Sync/Sync.test.js, renderer/src/modules/projects/Sync.js
Updated the tests for the Sync and moved the parse initialization to _app.js. #206
=> Updating the test

jsconfig.json, renderer/jsconfig.json, renderer/src/components/EditorPage/Navigation/reference/SelectBook.js, renderer/src/components/EditorPage/Navigation/reference/SelectVerse.js, renderer/src/modules/biblenavigation/BibleNavigation.js, renderer/src/util/convertToRange.js
- Handling book navigation with a boolean prop
- Ability to select multiple set of verses and displaying then in range value
- Toggling ability to unselect books
=> Ability To Multi Select Books or Verses

renderer/src/components/Login/Login.js, renderer/src/components/Login/useAuthentication.js, renderer/src/components/ProjectsPage/Profile/Profile.js, renderer/src/components/ProjectsPage/Profile/handleProfile.js, renderer/src/core/Login/handleJson.js, renderer/src/core/Login/handleLogin.js, renderer/src/layouts/TopMenuBar.js, renderer/src/modules/projects/Profile.js
Updated the profile with new UI,  added UX and enabled signout functionality. #205 
Works fine in the electron app.
=> Updated the profile with new UI

renderer/src/components/Login/useAuthentication.js, renderer/src/components/context/ProjectContext.js, renderer/src/core/projects/saveProjetcsMeta.js, renderer/src/util/createVersificationUSFM.js
Added all the offline backend connections for the first 2 pages of the App.
=> Did connection for offline flow

renderer/src/core/export/exportCSS.js, renderer/src/core/export/exportHTML.js
Added export to HTML functionality to export Bible from AG.  #230
=> adding export to HTML functionality

.eslintrc.json, renderer/pages/_document.js, renderer/pages/loader.css, renderer/src/components/EditorPage/Navigation/CustomNavigation.js, renderer/src/components/EditorPage/Navigation/reference/SelectBook.js, renderer/src/components/EditorPage/NewRefernce/ReferencePlaceholder.js, renderer/src/components/EditorPage/Reference/RefBible/RefBible.js, renderer/src/components/EditorPage/Reference/ReferenceCard.js, renderer/src/components/EditorPage/Reference/ResourcesPopUp.js, renderer/src/components/EditorPage/Reference/TranslationHelpsCard.js, renderer/src/components/Menubar/MenuBar.js, renderer/src/components/context/CustomNavigationContext.js, renderer/src/components/context/ReferenceContext.js, renderer/src/core/projects/fetchProjectsMeta.js, renderer/src/core/projects/saveProjetcsMeta.js, renderer/src/layouts/TopMenuBar.js, renderer/src/layouts/editor/AboutModal.js, renderer/src/layouts/editor/SubMenuBar.js, renderer/src/modules/biblenavigation/BibleNavigation.js, renderer/src/modules/editorsidebar/EditorSideBar.js, renderer/src/modules/projects/ProjectList.js, renderer/src/modules/projects/SmallEditorSection.js
- Demo snack bar component
- Translation notes, questions and word integration
- Fix for async read and write meta
=> Projects meta fetch fix and multiple translation helps resources

package-lock.json, renderer/src/components/hooks/projects/useProjectsSort.js, renderer/src/core/projects/fetchProjectsMeta.js, renderer/src/layouts/projects/TopMenuBar.js
Fetching all the projects (only with the burrito file) and store the metadata to localforage.
Displaying the projects on the Project List page.
All the data's been taken from the burrito, no need for the projects.json file anymore.
=> fetching SB for all the project related activities

renderer/src/components/ProjectsPage/CreateProject/AdvancedSettingsDropdown.js, renderer/src/components/ProjectsPage/CreateProject/TargetLanguagePopover.js, renderer/src/components/context/ProjectContext.js, renderer/src/components/hooks/projects/useProjectsSort.js, renderer/src/core/Login/handleJson.js, renderer/src/core/burrito/createTranslationSB.js, renderer/src/core/projects/fetchProjectsMeta.js, renderer/src/core/projects/saveProjectFiles.js, renderer/src/core/projects/saveProjetcsMeta.js, renderer/src/util/createVersificationUSFM.js
Linked burrito for creating a new project and listing the projects. 
Static user initialization is been changed to dynamic (completely depends on the user profile).
Did error handling and fixed minor bugs. #248
=> Linked burrito and did error handling

package-lock.json, package.json, renderer/environment.js, renderer/src/components/EditorPage/UsfmEditor/UsfmEditor.js, renderer/src/components/EditorPage/UsfmEditor/UsfmToolbar.js, renderer/src/components/context/ProjectContext.js, renderer/src/components/context/ReferenceContext.js, renderer/src/components/hooks/projects/useProjectsSort.js, renderer/src/core/editor/readFile.js, renderer/src/core/editor/writeToFile.js, renderer/src/core/projects/fetchProjectsMeta.js, renderer/src/core/reference/readRefBurrito.js, renderer/src/core/reference/readRefMeta.js, renderer/src/layouts/editor/SubMenuBar.js
- Burrito based read and write for **usfm** editor
- Navigation with burrito files
- Projects synchronous fix on **projects** list tab
- Custom separable ToolBar for **usfm** editor
=> Burrito-USFM editor

renderer/src/components/ProjectsPage/CreateProject/AdvancedSettingsDropdown.js, renderer/src/components/ProjectsPage/CreateProject/LicencePopover.js, renderer/src/components/ProjectsPage/CreateProject/TargetLanguagePopover.js, renderer/src/components/context/ProjectContext.js, renderer/src/core/burrito/createTranslationSB.js, renderer/src/core/projects/saveProjetcsMeta.js
Adding licence feature in New project page. #253 
fixed few UI issues.
=> Added the licence feature in New Project page.

renderer/src/components/ProjectsPage/Projects/EnhancedTableHead.js, renderer/src/components/hooks/projects/useProjectsSort.js, renderer/src/core/projects/fetchProjectsMeta.js, renderer/src/core/projects/saveProjetcsMeta.js, renderer/src/modules/projects/ProjectList.js, renderer/src/util/createVersificationUSFM.js
Storing extra project details in AG.json file (Things can't be added in Burrito).
Displaying all the required content in Project List. #248
=> Storing and Displaying project settings

main/index.js, package-lock.json, package.json, renderer/src/core/burrito/updateTranslationSB.js, renderer/src/layouts/projects/ExportProjectPopUp.js, renderer/src/modules/projects/ProjectList.js
Added the Export Bible with burrito feature on the project list page. #248
=> Adding Export complete Bible

renderer/environment.js, renderer/src/components/hooks/projects/useProjectsSort.js, renderer/src/core/projects/fetchProjectsMeta.js, renderer/src/core/projects/updateAgSettings.js, renderer/src/util/createVersificationUSFM.js
Updated the creation for autographa settings JSON file. #248 
Abel to do star and unstar then store it in ag-setting.json.
Display the contents from ag-settings.json to Project List for each project.
=> Did fixes for creating and updating ag settings

renderer/src/components/ProjectsPage/CreateProject/CustomCanonSpecification.js, renderer/src/components/ProjectsPage/CreateProject/TargetLanguagePopover.js, renderer/src/components/ProjectsPage/Projects/EnhancedTableHead.js, renderer/src/lib/AdvanceSettings.json, renderer/src/modules/projects/ProjectList.js
Control on Updating the static and dynamic data (Canon spec., Target language, Licence) in New Project Page. #248
=> Disable the edit on Static data

renderer/src/components/ProjectsPage/CreateProject/AdvancedSettingsDropdown.js, renderer/src/components/ProjectsPage/CreateProject/CustomCanonSpecification.js, renderer/src/components/context/ProjectContext.js
Made changes for the selection of canon specification to have only one custom canon in New Project Page and did the UI changes based on that. #248
=> Made changes for the selection of canon spec

renderer/src/components/SnackBar/SnackBar.js
Updating the SnackBar component.
=> Updating the snackbar component

renderer/src/components/context/ProjectContext.js
updated the user settings. #248
=> changed the user setting setup

renderer/src/components/Login/CustomLogin.js, renderer/src/components/Login/Login.js
=> Alpha fixes

renderer/src/core/burrito/importBurrito.js, renderer/src/core/projects/saveProjetcsMeta.js, renderer/src/layouts/projects/ImportProjectPopUp.js, renderer/src/layouts/projects/Layout.js
Validating the burrito using AJV before importing. #288
=> Updated import burrito code

renderer/src/layouts/projects/ExportProjectPopUp.js
Added field validation and SnackBar for displaying msgs. #248
=> Added field validation for Export

renderer/src/components/EditorPage/UsfmEditor/UsfmEditor.js, renderer/src/components/context/ProjectContext.js, renderer/src/components/context/ReferenceContext.js, renderer/src/layouts/editor/MenuBar.js, renderer/src/modules/editor/Editor.js
Fixed few Dom errors found while testing. #248
=> Fixed few flow issues

renderer/src/components/context/ProjectContext.js, renderer/src/components/context/ReferenceContext.js, renderer/src/components/hooks/projects/useProjectsSort.js, renderer/src/core/burrito/createTranslationSB.js, renderer/src/core/burrito/importBurrito.js, renderer/src/core/burrito/updateTranslationSB.js, renderer/src/core/projects/saveProjetcsMeta.js, renderer/src/modules/projects/CustomAutocomplete.js, renderer/src/modules/projects/NewProject.js, renderer/src/util/createVersificationUSFM.js
Updated the workflow of Import and Export of burrito, updating the keys on primary and upstream. 
Updating the revision number on export if there is a change in checksum #310 
Updated the New Project Page, removed the version and added project name abbreviation.
Fixed a few data matching issues. #309 
Using asterisks(*) for required fields in New Project Page and Profile #307
=> Updated the offline backend flow (import/export/burrito)

renderer/src/components/EditorPage/BookMarks/Bookmarks.js, renderer/src/components/EditorPage/Reference/ResourcesPopUp.js, renderer/src/components/EditorPage/UsfmEditor/UsfmEditor.js, renderer/src/components/Notification/CustomNofications.js, renderer/src/components/ProjectsPage/Projects/EnhancedTableHead.js, renderer/src/components/context/ReferenceContext.js, renderer/src/layouts/editor/EditorSection.js, renderer/src/layouts/editor/MenuBar.js, renderer/src/layouts/editor/SubMenuBar.js, renderer/src/layouts/projects/ExportProjectPopUp.js, renderer/src/layouts/projects/Layout.js, renderer/src/layouts/projects/TopMenuBar.js, renderer/src/modules/editor/Editor.js, renderer/src/modules/projects/NewProject.js, renderer/src/modules/projects/Profile.js, renderer/src/modules/projects/ProjectList.js, styles/style-override.lazy.css
Usability fixes and Enhancements
=> Usabilityfix

renderer/src/components/hooks/projects/useProjectsSort.js
Star/unstar doubling issue is been fixed #350
=> fixed the doubling issue with star/unstar

renderer/src/core/burrito/importBurrito.js, renderer/src/layouts/projects/ImportProjectPopUp.js, renderer/src/layouts/projects/TopMenuBar.js
Before importing an SB, the dialog box will have the project details and will validate the SB. #349 
Removed the page load from the title Autographa on page2 to fix the page reload issue (on the basis of Discussion). #351
=> Displaying the details of Burrito while import

package-lock.json, package.json
Updated the version from beta 2 to beta 3.
=> Updated the version to beta 3

renderer/src/components/Login/Login.js, renderer/src/components/ProjectsPage/CreateProject/AdvancedSettingsDropdown.js, renderer/src/modules/projects/NewProject.js
Synced UI changes with the functionality of the Login page and New Project page.
=> syncing new UI changes with the functionalities

renderer/pages/_app.js, renderer/src/components/EditorPage/BookMarks/Bookmarks.js, renderer/src/components/ProjectsPage/CreateProject/AdvancedSettingsDropdown.js, renderer/src/components/ProjectsPage/CreateProject/LicencePopover.js, renderer/src/components/context/ReferenceContext.js, renderer/src/layouts/editor/ConfirmationModal.js, renderer/src/layouts/editor/EditorSection.js, renderer/src/layouts/editor/MenuBar.js, renderer/src/layouts/editor/RowSection.js, renderer/src/layouts/projects/TopMenuBar.js, renderer/src/modules/editor/Editor.js, renderer/src/modules/projects/NewProject.js, renderer/src/modules/projects/Profile.js
- common resource fetch
- resource remove confirmation ui
- font fetch fix
- bookmark loading
=> Resource removal 

renderer/src/components/ProjectsPage/CreateProject/AdvancedSettingsDropdown.js, renderer/src/layouts/editor/MenuBar.js, renderer/src/layouts/projects/ExportProjectPopUp.js, renderer/src/layouts/projects/ImportProjectPopUp.js, renderer/src/modules/projects/ImportPopUp.js, renderer/src/modules/projects/ProjectList.js
Fixed the issue with the down arrow in Project List.
Added the checkbox for the validation in Import burrito metadata validation.
Did some UI fixes in Export and Import popups.
=> Fixing some UI issues and alignments

renderer/src/components/ProjectsPage/CreateProject/AdvancedSettingsDropdown.js, renderer/src/modules/projects/ProjectList.js
Fixed the issue with Custom canon selection on the Edit  Project page and updated the states on the ProjectList page after editing the project.
=> Fixed issue with canon spec

.eslintrc.json, next.config.js, package-lock.json, package.json, renderer/pages/home.js, renderer/src/components/EditorPage/BookMarks/Bookmarks.js, renderer/src/components/EditorPage/Navigation/CustomNavigation.js, renderer/src/components/EditorPage/Reference/ImportResource.js, renderer/src/components/EditorPage/Reference/ReferenceBible/ReferenceBible.js, renderer/src/components/EditorPage/Reference/ResourcesPopUp.js, renderer/src/components/EditorPage/UsfmEditor/CustomUsfmToolbar.js, renderer/src/components/EditorPage/UsfmEditor/UsfmEditor.js, renderer/src/components/Login/Login.js, renderer/src/components/Notification/CustomNofications.js, renderer/src/components/ProjectsPage/CreateProject/CustomCanonSpecification.js, renderer/src/components/Sync/Dropzone/Dropzone.js, renderer/src/core/projects/saveProjetcsMeta.js, renderer/src/layouts/editor/EditorSection.js, renderer/src/layouts/editor/MenuBar.js, renderer/src/layouts/editor/SectionContainer.js, renderer/src/layouts/editor/SectionPlaceholder1.js, renderer/src/layouts/editor/SectionPlaceholder2.js, renderer/src/layouts/editor/SubMenuBar.js, renderer/src/layouts/projects/ExportProjectPopUp.js, renderer/src/modules/biblenavigation/BibleNavigation.js, renderer/src/modules/editor/Editor.js, renderer/src/modules/editorsidebar/EditCrossReference.js, renderer/src/modules/editorsidebar/EditFootnote.js, renderer/src/modules/projects/ImportPopUp.js, renderer/src/modules/projects/Profile.js
- Reverted non-functional features for the release 
- import fix on edit project
- eslint settings update
=> Beta4release

renderer/src/core/burrito/importBurrito.js, renderer/src/layouts/editor/ConfirmationModal.js, renderer/src/layouts/editor/EditorSection.js, renderer/src/layouts/editor/SectionContainer.js, renderer/src/layouts/projects/ImportProjectPopUp.js
Adding a Project replace feature while Importing the same project which already exists in the list.
Updated the ConfirmationModel component.
=> Replace on import

renderer/src/components/ProjectsPage/CreateProject/AdvancedSettingsDropdown.js
Fixed the Custom selection issue in Scope. #380
=> fixed the selection issue with Custom option

renderer/src/components/ProjectsPage/CreateProject/AdvancedSettingsDropdown.js
Fixed:- In New/Edit Project page expand /collapse arrow not changing for Advanced settings. #383
=> Fixed arrow issue

renderer/src/components/hooks/useValidator.js, renderer/src/modules/projects/NewProject.js
Added the validation hook and connected with New Project.
=> Adding the validation hook

renderer/src/Home.js, renderer/src/components/Login/useAuthentication.js, renderer/src/components/MenuDropdown/MenuDropdown.js, renderer/src/components/ProjectsPage/CreateProject/AdvancedSettingsDropdown.js, renderer/src/components/ProjectsPage/CreateProject/CustomCanonSpecification.js, renderer/src/components/ProjectsPage/CreateProject/TargetLanguagePopover.js, renderer/src/components/context/ProjectContext.js, renderer/src/components/hooks/projects/useProjectsSort.js, renderer/src/components/hooks/useValidator.js, renderer/src/core/Login/handleLogin.js, renderer/src/core/burrito/createTranslationSB.js, renderer/src/core/burrito/importBurrito.js, renderer/src/core/burrito/updateTranslationSB.js, renderer/src/core/editor/writeToFile.js, renderer/src/core/projects/fetchProjectsMeta.js, renderer/src/core/projects/handleProfile.js, renderer/src/core/projects/saveProjetcsMeta.js, renderer/src/core/projects/updateAgSettings.js, renderer/src/core/reference/readIngredients.js, renderer/src/core/reference/readRefBurrito.js, renderer/src/layouts/projects/ExportProjectPopUp.js, renderer/src/layouts/projects/ImportProjectPopUp.js, renderer/src/modules/projects/ImportPopUp.js, renderer/src/modules/projects/NewProject.js, renderer/src/modules/projects/Profile.js, renderer/src/modules/projects/ProjectList.js, renderer/src/util/createVersificationUSFM.js, renderer/src/util/validate.js
Added the logs for the entire App. #305
=> Adding the logs for the App

package-lock.json, package.json, renderer/src/components/EditorPage/Reference/ResourceOption.js, renderer/src/components/EditorPage/Reference/ResourcesPopUp.js, renderer/src/components/context/ProjectContext.js, renderer/src/core/reference/manifest.yaml, renderer/src/core/reference/readCustomResources.js, renderer/src/core/reference/readmanifest.js, renderer/src/core/reference/writeCustomResources.js, renderer/src/layouts/editor/SectionContainer.js
- Adding custom resources using URLs
- Resolved urls
=> Custom resource

e2e-tests/base.test.ts, renderer/src/components/EditorPage/Navigation/CustomNavigation.js, renderer/src/components/EditorPage/Reference/ResourcesPopUp.js, renderer/src/components/Menubar/MenuBar.js, renderer/src/components/Notification/CustomNofications.js, renderer/src/layouts/editor/AboutModal.js, renderer/src/layouts/editor/EditorSection.js, renderer/src/layouts/editor/MenuBar.js, renderer/src/layouts/editor/SubMenuBar.js, renderer/src/modules/biblenavigation/BibleNavigation.js, renderer/src/modules/editor/Editor.js, renderer/src/modules/editorsidebar/EditorSideBar.js, renderer/src/modules/notifications/Notifications.js, renderer/src/modules/projects/NewProject.js
Added the test cases for the editor page.
=> Adding test cases for 3rd Page

renderer/src/components/ProjectsPage/CreateProject/AdvancedSettingsDropdown.js, renderer/src/components/context/ProjectContext.js
Updated the code for user settings.
=> Updated the code for user settings

e2e-tests/base.test.ts, next.config.js, package.json, renderer/src/components/EditorPage/Reference/ResourcesPopUp.js, renderer/src/components/EditorPage/Reference/TranslationHelps.js, renderer/src/components/ProjectsPage/CreateProject/TargetLanguagePopover.js, renderer/src/components/context/ProjectContext.js, renderer/src/layouts/editor/EditorSection.js, renderer/src/layouts/editor/SectionPlaceholder1.js, renderer/src/layouts/editor/SectionPlaceholder2.js
- Build fix
- Multiple resource owner fix
=> Custom resourcename

main/index.js, package-lock.json
=> removing the win menu

renderer/src/components/EditorPage/Reference/ImportResource.js, renderer/src/layouts/editor/SectionPlaceholder2.js
Fixed the issue with import/upload bible as resource.
=> Fixed the reference bible upload issue

renderer/src/components/EditorPage/UsfmEditor/UsfmEditor.js
Added the script to update the last seen while editing the content in the Editor pane. #384
=> Updating the last seen

renderer/src/components/ProjectsPage/CreateProject/LicencePopover.js
Switched the functionality of the licence preview button.
#412
=> switched the toggle function

renderer/src/layouts/projects/Layout.js, renderer/src/modules/projects/CustomList.js, renderer/src/modules/projects/Profile.js, renderer/src/modules/projects/SearchTags.js, styles/style-override.lazy.css
#385 has been fixed(Scrollable dropdown)
#328 show scrollbar new project page
#381 app language dropdown my profile page
#422 searching if text is entered
=> issue resolved #385

renderer/src/components/Login/Login.js, renderer/src/modules/projects/ImportPopUp.js
Fixed the SVG loading issues #280 and #411 -1
Need help from Arpit to fix the loading of colour in a SVG on the login page.
=> fixing svg loading issue

renderer/src/components/Login/CustomLogin.js, renderer/src/components/Login/Login.js
Fixed issue #421 
login page center align items
On clicking name button login insead of right arrow badge in button for easy clicking
=> Fixed issue #421 login page center align items

package-lock.json, package.json, renderer/src/components/Login/Login.js, renderer/src/modules/projects/Profile.js
Updating app version for release and fixed the lint errors.
=> Updating app version for release

renderer/src/core/burrito/importBurrito.js, renderer/src/layouts/projects/ImportProjectPopUp.js
Display a proper msg to the user while importing the bible project with a different version of the scripture burrito. #418
=> Displaying a proper msg while importing bible

renderer/src/Home.js, renderer/src/components/Login/useAuthentication.js, renderer/src/modules/projects/Profile.js, renderer/src/modules/projects/SearchTags.js
=> Logout fix

renderer/src/components/ProjectsPage/CreateProject/CustomCanonSpecification.js
#443 added Ok button in book selector dailog box
=> added ok button #443

package-lock.json, package.json
Updating the version from 2.0.1-beta to 2.0.1 in package.json
=> Updating the version in package.json

renderer/src/components/SnackBar/SnackBar.js, renderer/src/modules/biblenavigation/BibleNavigation.js
#453 usfm editor heading
#442 project message toaster
=> usfm editor heading #453

renderer/src/layouts/projects/ExportProjectPopUp.js
Fixed issue #329, added the validation for the export location.
=> validating the export location

renderer/src/components/EditorPage/BookMarks/Bookmarks.js, renderer/src/components/EditorPage/UsfmEditor/UsfmEditor.js
=> fixed issue 455 and deletion of data

package-lock.json, package.json
updating the version from 2.0.1 to 2.0.2 for release
=> updating the version to 2.0.2 for release

renderer/src/components/Login/Login.js
Defaulting the app to the offline mode.
=> Defaulting to offline mode

renderer/src/components/EditorPage/Reference/ImportResource.js, renderer/src/components/EditorPage/Reference/ResourcesPopUp.js, renderer/src/core/burrito/importBurrito.js, renderer/src/layouts/projects/ImportProjectPopUp.js
Did refactoring the code in the ResourcesPopUp component.
added a loader and status for showing the result of uploading data. #466
=> Refactoring the code in the ResourcesPopUp component

renderer/src/core/burrito/importBurrito.js, renderer/src/core/burrito/updateTranslationSB.js, renderer/src/layouts/editor/EditorSection.js, renderer/src/layouts/projects/ExportProjectPopUp.js, renderer/src/layouts/projects/ImportProjectPopUp.js, renderer/src/modules/projects/NewProject.js
Fixed the lint issues, DOM error while project creation and removed unwanted code from burrito while importing else the validation will fail.
=> Fixing lint issues, DOM error

renderer/src/components/EditorPage/Reference/ReferenceBible/ReferenceBible.js, renderer/src/components/context/ReferenceContext.js, renderer/src/core/projects/updateAgSettings.js, renderer/src/layouts/editor/EditorSection.js, renderer/src/layouts/editor/MenuBar.js, renderer/src/layouts/editor/SectionPlaceholder1.js, renderer/src/layouts/editor/SectionPlaceholder2.js, renderer/src/layouts/editor/SubMenuBar.js
Fixed the issue #448 
- Storing and retrieving of reference resources data.
- Handling columns and rows i.e. layouts and sections.
- Saving reference data's automatically to ag-settings.
- The editor page restarts from where the user left.
- Storing and retrieving of Translation Helps data.
=> Fixed the issue with reference storing and retrieving

renderer/src/components/EditorPage/ObsEditor/EditorPanel.js, renderer/src/components/EditorPage/ObsEditor/ReferenceObs.js, renderer/src/components/EditorPage/ObsEditor/core.js, renderer/src/components/context/ReferenceContext.js, renderer/src/layouts/editor/SectionPlaceholder1.js, renderer/src/layouts/editor/SectionPlaceholder2.js
Implemented the reference panel for loading the OBS resources and highlighted the content on the basis of editor content.
=> Adding the reference panel for OBS contents

renderer/src/modules/projects/ProjectList.js
Bug Fix 
- Edit and Export Project Box Position in Project List page
=> fix for edit/export box position in ProjectList

renderer/src/modules/projects/ProjectList.js
Bug Fix
- Edit Box Position issue for starred Project
=> fixed edit box position issue for starred project

renderer/src/components/ProjectsPage/CreateProject/AdvancedSettingsDropdown.js, renderer/src/core/projects/saveProjetcsMeta.js, renderer/src/modules/projects/ImportPopUp.js, renderer/src/util/createObsContent.js, renderer/src/util/createVersificationUSFM.js
BUG
- Starred Project become unstarred after edit project ( OBS and Translation )
=> fixed starred project unstarred after edit the project

renderer/src/util/createObsContent.js
BUG
- Moved License OBS to inside of content folder
=> moved creation of OBS License inside content Directory

renderer/src/components/EditorPage/Reference/OBS/ObsResourceCard.js, renderer/src/components/EditorPage/Reference/OBS/ObsTn.js, renderer/src/components/EditorPage/Reference/OBS/getObsTn.js, renderer/src/components/EditorPage/Reference/ResourcesPopUp.js, renderer/src/components/EditorPage/Reference/TranslationHelps.js, renderer/src/components/context/ProjectContext.js, renderer/src/core/reference/readCustomResources.js, renderer/src/core/reference/writeCustomResources.js, renderer/src/layouts/editor/SectionPlaceholder1.js, renderer/src/layouts/editor/SectionPlaceholder2.js
Import option for adding the OBS-tn from door43 and to display it in the reference pane
=> Fetching the OBS-tn from door43 to reference pane

package-lock.json, renderer/src/util/createObsContent.js, yarn.lock
- Bug Fix 
- Edit Project Recreate all contents of story
=> edit project replace all stories fixed

renderer/src/components/ProjectsPage/CreateProject/LicencePopover.js, renderer/src/modules/projects/ProjectList.js
-  license popover close issue 
- export option not showing for last item in listing project
=> fixed bugs

renderer/src/components/EditorPage/ObsEditor/EditorPanel.js, renderer/src/components/EditorPage/ObsEditor/ReferenceObs.js
- added numbering for story sections on reference and editor
=> OBS Story Numbering

package-lock.json, renderer/src/components/EditorPage/Reference/OBS/getObsTn.js, renderer/src/components/EditorPage/Reference/ResourcesPopUp.js, renderer/src/components/EditorPage/Reference/TranslationHelps.js, renderer/src/translations/en.js
#502 added OBS translation questions
=> Adding OBS translation questions

renderer/src/components/ProjectsPage/CreateProject/TargetLanguagePopover.js, renderer/src/layouts/projects/Layout.js, renderer/src/modules/projects/CustomList.js
Fixed 
Greyed out the versification scheme box on the Edit project page.
Changed the logo(from upload to download) for the Import burrito on the Project List page.
#576
=> Fixing the bugs on New/Edit project page

renderer/src/components/ProjectsPage/CreateProject/TargetLanguagePopover.js, renderer/src/layouts/editor/SubMenuBar.js
Since we are not allowing to do bookmarks we are removing bookmarks from OBS mode.
=> removing bookmarks from OBS mode

renderer/src/components/EditorPage/Reference/ImportResource.js
=> Fixed the issue with resource import

renderer/src/components/EditorPage/UsfmEditor/UsfmEditor.js
Updated the code to change the tN with the verse change #577
=> fixed the bug, tN is working with verse change

renderer/src/modules/projects/NewProject.js
Enabled script direction for the OBS editor. #587
=> Enabled RTL and LTR directions for OBS

main/index.js, renderer/src/components/EditorPage/Reference/TA/TaNavigation.js, renderer/src/layouts/editor/EditorSection.js
#590 dropdown tooltip fixed base on app size
=> ta dropdown width responsive

renderer/src/components/EditorPage/ObsEditor/ObsEditor.js, renderer/src/components/EditorPage/ObsEditor/core.js, renderer/src/core/burrito/updateObsSB.js, renderer/src/core/projects/fetchProjectsMeta.js, renderer/src/core/projects/updateAgSettings.js, renderer/src/modules/projects/ProjectList.js, renderer/src/util/createObsContent.js
Updated the directory name of OBS content to ingredients.
Enabled the process to import, export or process any obs project with different folder names.
=> Updated the directory name of OBS content to ingredients

renderer/src/components/ProjectsPage/CreateProject/TargetLanguagePopover.js, renderer/src/modules/projects/NewProject.js
**Bug Fix Language Dropdown**
- Warning on duplicate language creation 
- Filter for language display
=> fixed duplicate language creation and loading issue

renderer/src/components/EditorPage/Navigation/reference/SelectReference.module.css, renderer/src/components/ProjectsPage/CreateProject/CustomCanonSpecification.js, renderer/src/modules/projects/ImportPopUp.js
fixed #596 fixed displaying books
fixed in import books in a new project
fixed in advanced setting ->  all books, NT, OT and Custom books
=> fixed #596 displaying books

renderer/src/components/Login/CustomLogin.js
=> fixed Login button

renderer/src/components/Profile/UserProfile.js, renderer/src/components/hooks/useGetUserName.js, renderer/src/layouts/editor/MenuBar.js, renderer/src/layouts/projects/TopMenuBar.js
Display current username on the project list and project page. fixes #473
=> Display current username  

renderer/src/Home.js, renderer/src/components/context/ProjectContext.js, renderer/src/core/Login/handleJson.js
#612 3rd task done (licence.find())
=> licence task solved

renderer/src/components/AudioRecorder/components/Player.js, renderer/src/layouts/editor/SectionPlaceholder1.js, renderer/src/layouts/editor/SectionPlaceholder2.js, renderer/src/modules/editor/Editor.js
=> audio ui done

renderer/src/core/projects/saveProjetcsMeta.js, renderer/src/modules/projects/ImportPopUp.js, renderer/src/modules/projects/NewProject.js, renderer/src/util/createVersificationUSFM.js, yarn.lock
Adding text import feature in Audio mode
=> adding text import feature in Audio mode

renderer/src/util/createAudioVersification.js
Fixing sync details in Audio Projects
=> Fixing sync details in Audio Projects

renderer/src/components/AudioRecorder/components/WaveForm.js
Fixing the waveform loading issue
=> Fixing waveform loading issue

renderer/src/layouts/projects/ExportProjectPopUp.js
Added an option to export text along with Audio #557
=> Added an option to export text along with Audio

renderer/src/core/burrito/importBurrito.js, renderer/src/layouts/projects/ExportProjectPopUp.js
Added an option to import text along with the Audio project and fixed the issue with export
=> Added an option to import text along with Audio project

renderer/src/components/EditorPage/Reference/ImportResource.js
Added import text feature along with Audio project in Resouces import
=> Added import text along with Audio project in Resouces import

package-lock.json, package.json
updating the version to 2.2.0-beta.2
=> updating the version to 2.2.0-beta.2

renderer/src/components/Profile/UserProfile.js, renderer/src/components/ProjectsPage/CreateProject/LicencePopover.js, renderer/src/layouts/projects/SideBar.js
Updating code from <a> to <Link> for Next 13
=> Updating code with <Link>

.github/workflows/node.js.yml
updating the build flow with dmg-licence package
=> updating the flow with dmg-licence

renderer/src/components/AudioRecorder/components/EditorPage.js, renderer/src/components/AudioRecorder/components/Player.js, renderer/src/components/EditorPage/AudioEditor/MainPlayer.js
Fixed Takes order:-  Will refresh when we move to the next verse.
The active verse is visible.
Audio settings will open for Windows
=> Adding few enhancement to the Audio mode

package-lock.json, package.json
version updating to 2.2.0-beta.3
=> version updating to 2.2.0-beta.3

pages/wip/WaveForm.js, pages/wip/editor-audio.js
Adding the UI for the Audio Editor and WaveForm
=> Adding the UI for the Audio Editor and WaveForm

renderer/src/components/AudioRecorder/components/WaveForm.js
Fixing the audio playing issue after rerecording the audio.
=> Fixing the play button issue after retake

renderer/src/components/EditorPage/Reference/ImportResource.js
Fixing the issue with Reference Audio Import #683
=> Fixing the issue with Reference Audio Import

renderer/src/components/Sync/Gitea/GiteaUtils.js, renderer/src/core/burrito/importBurrito.js
fix for import project failed for older versions , because sync section not in the ag-settings and issue for creating also if not exist.
=> Fix/Import project - agsettings sync issue 

renderer/src/components/EditorPage/Scribex/Editor.jsx, renderer/src/components/EditorPage/Scribex/Scribex.jsx
fixing build issue related to lint
=> fixing build issue
